apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: edge-ingress
  namespace: default
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: collection-api
          servicePort: 80
