openapi: "3.0.2"

info:
  title: Collection Micro Service
  version: "1.0"
servers:
  - url: /v1.0

paths:
  /greeting/{name}:
    get:
      summary: Generate greeting
      description: Generates a greeting message.
      operationId: api.api.get_greeting
      responses:
        200:
          description: greeting response
          content:
            text/plain:
              schema:
                type: string
                example: "Hello World!"
      parameters:
        - name: name
          in: path
          description: Name of the person to greet.
          required: true
          schema:
            type: string
            example: "World"