apiVersion: v1
kind: Service
metadata:
  name: collection-api
spec:
  type: LoadBalancer
  selector:
    app: collection-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: collection-api
  labels:
    app: collection-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: collection-api
  template:
    metadata:
      labels:
        app: collection-api
    spec:
      containers:
      - name: collection-api
        image: collection-api
        ports:
        - containerPort: 80